### ISSUE TITLE
Cannot run the sourcebase from new clone

### ISSUE THREAD

**Issue by kelvin-dev** [react-native-training/react-native-elements-app#235]
Hi team, please help revise the README and help resolve the issue;

```
Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.
at node_modules\react-native\Libraries\LogBox\LogBox.js:117:10 in registerWarning
at node_modules\react-native\Libraries\LogBox\LogBox.js:63:8 in warnImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:36:4 in console.warn
at node_modules\expo\build\environment\react-native-logs.fx.js:18:4 in warn
at node_modules\react-native\Libraries\ReactNative\AppRegistry.js:200:6 in runApplication
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
at [native code]:null in callFunctionReturnFlushedQueue

TypeError: undefined is not an object (evaluating '_expoModulesCore.NativeModulesProxy.ExpoSplashScreen')
at node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
at node_modules\regenerator-runtime\runtime.js:165:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

```
D:\Demos\react-native-elements-app>react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.17.4 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - D:\Roaming\npm\yarn.CMD
    npm: 6.14.5 - D:\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 18.1.5063045
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30907.101 (Visual Studio Professional 2019)
  Languages:
    Java: 14.0.1 - /cygdrive/c/Program Files/OpenJDK/jdk-14.0.1/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    react-native-windows: Not Found
```
Cheers,

**Comment by arpitBhalla** [comment]
Hey, demo app has been migrated to the main repo, 
Follow this guide to setup locally 
https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/repo/contributing.md#setup

**Comment by kelvin-dev** [comment]
> Hey, demo app has been migrated to the main repo, Follow this guide to setup locally https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/repo/contributing.md#setup

Dear bro, there is still be problem from the main repo, would you please update the README guide

```
Could not resolve "@expo/vector-icons/Zocial" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.

Could not resolve "@expo/vector-icons/Octicons" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/MaterialIcons" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/MaterialCommunityIcons" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.     
Could not resolve "@expo/vector-icons/Ionicons" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/Foundation" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/EvilIcons" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/Entypo" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/FontAwesome" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/FontAwesome5" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/SimpleLineIcons" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/Feather" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/AntDesign" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/Fontisto" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.
Could not resolve "@expo/vector-icons/MaterialIcons" in file D:\Demos\react-native-elements\packages\themed\src\helpers\getIconType.tsx.

Could not resolve "@expo/vector-icons/EvilIcons" in file D:\Demos\react-native-elements\packages\base\dist\helpers\getIconType.js.
Could not resolve "@expo/vector-icons/Entypo" in file D:\Demos\react-native-elements\packages\base\dist\helpers\getIconType.js.  
Could not resolve "@expo/vector-icons/FontAwesome" in file D:\Demos\react-native-elements\packages\base\dist\helpers\getIconType.e.js.js.                                                                                                                              etIconType.js.       
Could not resolve "@expo/vector-icons/FontAwesome5" in file D:\Demos\react-native-elements\packages\base\dist\helpers\getIconType.js.                                                                                                                             s.
Could not resolve "@expo/vector-icons/SimpleLineIcons" in file D:\Demos\react-native-elements\packages\base\dist\helpers\getIconT.ype.js.
Could not resolve "@expo/vector-icons/Feather" in file D:\Demos\react-native-elements\packages\base\dist\helpers\getIconType.js. js.
Could not resolve "@expo/vector-icons/AntDesign" in file D:\Demos\react-native-elements\packages\base\dist\helpers\getIconType.js.js..                                                                                                                                ype.js.

Could not resolve "@expo/vector-icons/Fontisto" in file D:\Demos\react-native-elements\packages\base\dist\helpers\getIconType.js..
Could not resolve "@expo/vector-icons/MaterialIcons" in file D:\Demos\react-native-elements\packages\base\dist\helpers\getIconType.js.                                                                                                                            e.js.

Android Bundling complete 39325ms
```

which may cause blank screen issue

![screenshot-2022-01-16_04 26 25 461](https://user-images.githubusercontent.com/19224355/149638234-f6f80127-71b1-4635-816d-caa4accb5743.png)
